services:
  - type: web
    name: dental-age-estimation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dental-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src/.pythonlibs/lib/python3.12/site-packages
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

databases:
  - name: dental-db
    plan: free
    databaseName: dental_scheduler
    user: dental_user